name: ubuntu-builder psibase-cli container

env:
  GITHUB_OUTPUT: ""

on:
  workflow_dispatch:
    inputs:
        psinode-version:
          description: 'Psinode version'
          required: true

jobs:
  ubuntu-builder:
    name: psibase-cli_image_builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 0

      - name: Preparation
        id: prep
        run: |
          REGISTRY="ghcr.io"
          IMAGE="${REGISTRY}/${{ github.repository_owner }}/psibase-cli"
          TAGS="${IMAGE}:${{ github.sha }},${IMAGE}:${{ github.event.inputs.psinode-version }}"
          echo "tags=${TAGS,,}" >> $GITHUB_OUTPUT
      - name: Showtag
        id: showtag
        run: echo ${{ steps.prep.outputs.tags }}

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          pull: true
          build-args: VERSION=${{ github.event.inputs.psinode-version }}
          file: Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
